### ISSUE TITLE
Crash CircularCountDownTimer

### ISSUE THREAD

**Issue by n2ng-dev** [sahibul-nf/quran_app#4]
Hiii bang @sahibul-nf 
Countdown timer crash pada saat waktu pergantian jadwal shalat, jadi jika countdown nya 0 dia crash.

error :  'package:circular_countdown_timer/circular_countdown_timer.dart': Failed assertion: line 112 pos 15: 'initialDuration <= duration': is not true.

![image](https://github.com/sahibul-nf/hiQuran/assets/12078569/84db16e0-d068-4df4-b6b3-942c03f25532)

Terimakasih

**Comment by sahibul-nf** [comment]
branch yang mana yang kamu test?

**Comment by n2ng-dev** [comment]
branch yang master bang

**Comment by sahibul-nf** [comment]
coba branch Dev paling up to date

**Comment by sahibul-nf** [comment]
selama ini saya pake di device saya gada masalah sih (yang dari branch Dev)

**Comment by n2ng-dev** [comment]
Apa ada build apk dari branch Dev ?
sy coba build banyak error

**Comment by sahibul-nf** [comment]
kemungkinan beda versi flutter, seingat saya project ini menggunakan versi Flutter 3.7.5

Ini link apk nya:
https://www.icloud.com/iclouddrive/05fSa9nxFxO5wU6B7N-T1P2KQ#app-release
